import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';
import Head from 'next/head';

export const metadata = {
  title: 'dscvr-quiz-blink',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="dscvr:canvas:version" content="vNext" />
        <meta
          name="og:image"
          content="https://my-canvas.com/preview-image.png"
        />
      </Head>
      <head>
        <meta name="dscvr:canvas:version" content="vNext" />
        <meta
          name="og:image"
          content="https://my-canvas.com/preview-image.png"
        />
      </head>
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
